server:
  port: 7000

spring:
  application:
    name: gulimall-ware
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.149.130:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
